sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - ./bin/phpunit
  - ./bin/php-cs-fixer fix -v --diff --dry-run
